namespace HMCSEngine
{
    public enum VKeyCodes : byte
    {
        None = 0x00,

        LeftMouse = 0x01,
        RightMouse,

        MiddleMouse = 0x04,
        MouseX1,
        MouseX2,

        Backspace = 0x08,
        Tab,

        Clear = 0x0C,
        Return,

        Shift = 0x10,
        Control,
        Alt,
        Pause,
        Capslock,

        Escape = 0x1B,

        Space = 0x20,
        PageUp,
        PageDown,
        End,
        Home,
        LeftArrow,
        UpArrow,
        RightArrow,
        DownArrow,
        Select,

        Print = 0x2A,
        Execute,
        PrintScreen,
        Insert,
        Delete,
        Help,

        Alpha0 = 0x30,
        Alpha1,
        Alpha2,
        Alpha3,
        Alpha4,
        Alpha5,
        Alpha6,
        Alpha7,
        Alpha8,
        Alpha9,

        A = 0x41,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftWindows,
        RightWindows,
        Application,

        Sleep = 0x5F,
        Numpad0,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        Multiply,
        Add,
        Seperator,
        Subtract,
        Decimal,
        Divide,
        Function1,
        Function2,
        Function3,
        Function4,
        Function5,
        Function6,
        Function7,
        Function8,
        Function9,
        Function10,
        Function11,
        Function12,
        Function13,
        Function14,
        Function15,
        Function16,
        Function17,
        Function18,
        Function19,
        Function20,
        Function21,
        Function22,
        Function23,
        Function24,

        NumLock = 0x90,
        ScrollLock,

        LeftShift = 0xA0,
        RightShift,
        LeftControl,
        RightControl,
        LeftAlt,
        RightAlt,

        OEMColon = 0xBA,
        OEMEquals,
        OEMComma,
        OEMMinus,
        OEMFullStop,
        OEMForwardSlash,
        OEMGraveAccent,
        OEMLeftBrace = 0xDB,
        OEMBackwardsSlash,
        OEMRightBrace,
        OEMApostrophe,
        OEMCSAKeyboardRightControl
    }
}
